import type { SkillTag } from "./constants";

export type ToeicLesson = {
  id: string;
  title: string;
  titleVi: string;
  section: "listening" | "reading";
  part: number;
  skillTag: SkillTag;
  level: string;
};

export const TOEIC_LESSONS: ToeicLesson[] = [
  {
    id: "TL-001",
    title: "Lesson 1 Part 1",
    titleVi: "Bài 1 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-002",
    title: "Lesson 2 Part 1",
    titleVi: "Bài 2 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-003",
    title: "Lesson 3 Part 1",
    titleVi: "Bài 3 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-004",
    title: "Lesson 4 Part 1",
    titleVi: "Bài 4 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-005",
    title: "Lesson 5 Part 1",
    titleVi: "Bài 5 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-006",
    title: "Lesson 6 Part 1",
    titleVi: "Bài 6 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-007",
    title: "Lesson 7 Part 1",
    titleVi: "Bài 7 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-008",
    title: "Lesson 8 Part 1",
    titleVi: "Bài 8 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-009",
    title: "Lesson 9 Part 1",
    titleVi: "Bài 9 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-010",
    title: "Lesson 10 Part 1",
    titleVi: "Bài 10 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-011",
    title: "Lesson 11 Part 1",
    titleVi: "Bài 11 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-012",
    title: "Lesson 12 Part 1",
    titleVi: "Bài 12 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-013",
    title: "Lesson 13 Part 1",
    titleVi: "Bài 13 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-014",
    title: "Lesson 14 Part 1",
    titleVi: "Bài 14 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-015",
    title: "Lesson 15 Part 1",
    titleVi: "Bài 15 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-016",
    title: "Lesson 16 Part 1",
    titleVi: "Bài 16 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-017",
    title: "Lesson 17 Part 1",
    titleVi: "Bài 17 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-018",
    title: "Lesson 18 Part 1",
    titleVi: "Bài 18 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-019",
    title: "Lesson 19 Part 1",
    titleVi: "Bài 19 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-020",
    title: "Lesson 20 Part 1",
    titleVi: "Bài 20 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-021",
    title: "Lesson 21 Part 1",
    titleVi: "Bài 21 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-022",
    title: "Lesson 22 Part 1",
    titleVi: "Bài 22 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-023",
    title: "Lesson 23 Part 1",
    titleVi: "Bài 23 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-024",
    title: "Lesson 24 Part 1",
    titleVi: "Bài 24 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-025",
    title: "Lesson 25 Part 1",
    titleVi: "Bài 25 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-026",
    title: "Lesson 26 Part 1",
    titleVi: "Bài 26 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-027",
    title: "Lesson 27 Part 1",
    titleVi: "Bài 27 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-028",
    title: "Lesson 28 Part 1",
    titleVi: "Bài 28 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-029",
    title: "Lesson 29 Part 1",
    titleVi: "Bài 29 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-030",
    title: "Lesson 30 Part 1",
    titleVi: "Bài 30 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-031",
    title: "Lesson 31 Part 1",
    titleVi: "Bài 31 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-032",
    title: "Lesson 32 Part 1",
    titleVi: "Bài 32 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-033",
    title: "Lesson 33 Part 1",
    titleVi: "Bài 33 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-034",
    title: "Lesson 34 Part 1",
    titleVi: "Bài 34 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-035",
    title: "Lesson 35 Part 1",
    titleVi: "Bài 35 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-036",
    title: "Lesson 36 Part 1",
    titleVi: "Bài 36 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-037",
    title: "Lesson 37 Part 1",
    titleVi: "Bài 37 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-038",
    title: "Lesson 38 Part 1",
    titleVi: "Bài 38 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-039",
    title: "Lesson 39 Part 1",
    titleVi: "Bài 39 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "listening-detail",
    level: "B1",
  },
  {
    id: "TL-040",
    title: "Lesson 40 Part 1",
    titleVi: "Bài 40 Phần 1",
    section: "listening",
    part: 1,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-041",
    title: "Lesson 41 Part 5",
    titleVi: "Bài 41 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-042",
    title: "Lesson 42 Part 5",
    titleVi: "Bài 42 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-043",
    title: "Lesson 43 Part 5",
    titleVi: "Bài 43 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-044",
    title: "Lesson 44 Part 5",
    titleVi: "Bài 44 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-045",
    title: "Lesson 45 Part 5",
    titleVi: "Bài 45 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-046",
    title: "Lesson 46 Part 5",
    titleVi: "Bài 46 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-047",
    title: "Lesson 47 Part 5",
    titleVi: "Bài 47 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-048",
    title: "Lesson 48 Part 5",
    titleVi: "Bài 48 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-049",
    title: "Lesson 49 Part 5",
    titleVi: "Bài 49 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-050",
    title: "Lesson 50 Part 5",
    titleVi: "Bài 50 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-051",
    title: "Lesson 51 Part 5",
    titleVi: "Bài 51 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-052",
    title: "Lesson 52 Part 5",
    titleVi: "Bài 52 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-053",
    title: "Lesson 53 Part 5",
    titleVi: "Bài 53 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-054",
    title: "Lesson 54 Part 5",
    titleVi: "Bài 54 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-055",
    title: "Lesson 55 Part 5",
    titleVi: "Bài 55 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-056",
    title: "Lesson 56 Part 5",
    titleVi: "Bài 56 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-057",
    title: "Lesson 57 Part 5",
    titleVi: "Bài 57 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-058",
    title: "Lesson 58 Part 5",
    titleVi: "Bài 58 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-059",
    title: "Lesson 59 Part 5",
    titleVi: "Bài 59 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-060",
    title: "Lesson 60 Part 5",
    titleVi: "Bài 60 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-061",
    title: "Lesson 61 Part 5",
    titleVi: "Bài 61 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-062",
    title: "Lesson 62 Part 5",
    titleVi: "Bài 62 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-063",
    title: "Lesson 63 Part 5",
    titleVi: "Bài 63 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-064",
    title: "Lesson 64 Part 5",
    titleVi: "Bài 64 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-065",
    title: "Lesson 65 Part 5",
    titleVi: "Bài 65 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-066",
    title: "Lesson 66 Part 5",
    titleVi: "Bài 66 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-067",
    title: "Lesson 67 Part 5",
    titleVi: "Bài 67 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-068",
    title: "Lesson 68 Part 5",
    titleVi: "Bài 68 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-069",
    title: "Lesson 69 Part 5",
    titleVi: "Bài 69 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-070",
    title: "Lesson 70 Part 5",
    titleVi: "Bài 70 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-071",
    title: "Lesson 71 Part 5",
    titleVi: "Bài 71 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-072",
    title: "Lesson 72 Part 5",
    titleVi: "Bài 72 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-073",
    title: "Lesson 73 Part 5",
    titleVi: "Bài 73 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-074",
    title: "Lesson 74 Part 5",
    titleVi: "Bài 74 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-075",
    title: "Lesson 75 Part 5",
    titleVi: "Bài 75 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-076",
    title: "Lesson 76 Part 5",
    titleVi: "Bài 76 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-077",
    title: "Lesson 77 Part 5",
    titleVi: "Bài 77 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-078",
    title: "Lesson 78 Part 5",
    titleVi: "Bài 78 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-079",
    title: "Lesson 79 Part 5",
    titleVi: "Bài 79 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-080",
    title: "Lesson 80 Part 5",
    titleVi: "Bài 80 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-081",
    title: "Lesson 81 Part 5",
    titleVi: "Bài 81 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-082",
    title: "Lesson 82 Part 5",
    titleVi: "Bài 82 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-083",
    title: "Lesson 83 Part 5",
    titleVi: "Bài 83 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-084",
    title: "Lesson 84 Part 5",
    titleVi: "Bài 84 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-085",
    title: "Lesson 85 Part 5",
    titleVi: "Bài 85 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-086",
    title: "Lesson 86 Part 5",
    titleVi: "Bài 86 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-087",
    title: "Lesson 87 Part 5",
    titleVi: "Bài 87 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-088",
    title: "Lesson 88 Part 5",
    titleVi: "Bài 88 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-089",
    title: "Lesson 89 Part 5",
    titleVi: "Bài 89 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-090",
    title: "Lesson 90 Part 5",
    titleVi: "Bài 90 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-091",
    title: "Lesson 91 Part 5",
    titleVi: "Bài 91 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-092",
    title: "Lesson 92 Part 5",
    titleVi: "Bài 92 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-093",
    title: "Lesson 93 Part 5",
    titleVi: "Bài 93 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-094",
    title: "Lesson 94 Part 5",
    titleVi: "Bài 94 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-095",
    title: "Lesson 95 Part 5",
    titleVi: "Bài 95 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-096",
    title: "Lesson 96 Part 5",
    titleVi: "Bài 96 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-097",
    title: "Lesson 97 Part 5",
    titleVi: "Bài 97 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-098",
    title: "Lesson 98 Part 5",
    titleVi: "Bài 98 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-099",
    title: "Lesson 99 Part 5",
    titleVi: "Bài 99 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-100",
    title: "Lesson 100 Part 5",
    titleVi: "Bài 100 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
  {
    id: "TL-101",
    title: "Lesson 101 Part 5",
    titleVi: "Bài 101 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-102",
    title: "Lesson 102 Part 5",
    titleVi: "Bài 102 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-103",
    title: "Lesson 103 Part 5",
    titleVi: "Bài 103 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-104",
    title: "Lesson 104 Part 5",
    titleVi: "Bài 104 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "grammar",
    level: "B1",
  },
  {
    id: "TL-105",
    title: "Lesson 105 Part 5",
    titleVi: "Bài 105 Phần 5",
    section: "reading",
    part: 5,
    skillTag: "vocabulary",
    level: "B1",
  },
];

export function listLessons(): ToeicLesson[] {
  return TOEIC_LESSONS;
}

export function getLesson(id: string): ToeicLesson | undefined {
  return TOEIC_LESSONS.find((l) => l.id === id);
}
